# site settings
title: MiBacon
subtitle: michal bacon
email: michal.bacon@gmail.com
description: 
phone: 201-693-0370
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:



# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:

linkedin_url: 


# build settings
markdown: kramdown

sass:
  style: compressed

